show message error for static code analysis

diff --git a/.github/workflows/devops-solution-ci.yml b/.github/workflows/devops-solution-ci.yml
--- a/.github/workflows/devops-solution-ci.yml
+++ b/.github/workflows/devops-solution-ci.yml
@@ -51,7 +51,11 @@ jobs:
         name: Static Code Analysis
         run: 
           set +e
-          docker run $REPO pylint manage.py || true
+          docker run $REPO pylint manage.py
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ];
+            echo "Static Code Analysis failed with exit code $EXIT_CODE"
+          fi
           set -e
 
       - name: Code Coverage
